export const refs = {
  mainList: document.querySelector('.js-main-film-list'),
  dataNotFoundEl: document.querySelector('.js-not-film-card'),
  headerForm: document.querySelector('.header__form'),
  authBtn: document.querySelector('.auth-btn'),
  footerBtn: document.querySelector('.footer__btn'),
  loader: document.querySelector(`.js-page-loader`),
  headerWatchedBtn: document.querySelector('.js-watched'),
  headerQueueBtn: document.querySelector('.js-queue'),
  paginationBox: document.querySelector('.pagination_box'),
  errorMessage: document.getElementById('header__error-message'),
  trendingSection: document.querySelector(".swiper-section"),
  btnToTop: document.getElementById("up-btn"),
  aboutModal: document.querySelector('.js-about-modal'),
  body: document.querySelector('body'),
  btnOpenAboutModal: document.querySelector('.js-open-modal'),
  btnCloseAboutModal: document.querySelector('.js-close-about-modal'),
  swiperModal: document.querySelector('#swiper-modal'),
  libBtn: document.querySelector('.library__btns'),
  modal: document.querySelector('[data-backdrop]'),
  dataModalClose: document.querySelector('[data-modal-close]'),
  dataBackdrop: document.querySelector('[data-backdrop]'),
  changeTheme: document.querySelectorAll(`.change_theme`),
  changeThemeCssLink: document.querySelector(`[title= "theme"]`),
  swiperWrapper: document.querySelector('.swiper-wrapper'),
  swiperRef: document.querySelector('#trends-swiper'),
  autorizationChecked: document.getElementById('icon-autorization-checked')
};
